# -*- coding: utf-8 -*-
"""pca_on_mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q-9_k6S8f8727keq9-oxn3YGQ_vFl308
"""

from sklearn.datasets import fetch_openml
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

mnist = fetch_openml('mnist_784',version=1)

X=mnist.data
y=mnist.target

print("orignial shape of dataset : ",X.shape)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)
print("reduced shape after pca : ",X_pca.shape)

plt.figure(figsize=(8,6))
scatter = plt.scatter(
    X_pca[:,0],X_pca[:,1],c=y.astype(int),cmap='tab10',s=10
)
plt.colorbar(scatter)
plt.title("PCA on MNIST Dataset")
plt.xlabel("First Principal Component")
plt.ylabel("Second Principal Component")
plt.show()

