# -*- coding: utf-8 -*-
"""kmeans_on_iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1355sBvW065ogUM-QQOhDQwf-kqP4tST0
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.cluster import KMeans

iris = load_iris()

X = iris.data

print("Dataset Shape:", X.shape)

kmeans = KMeans(
    n_clusters=3,
    random_state=42
)

kmeans.fit(X)

labels = kmeans.labels_

print(labels)

centroids = kmeans.cluster_centers_

print("Centroids:\n")

print(centroids)

plt.figure(figsize=(8,6))

plt.scatter(
    X[:,0],
    X[:,1],
    c=labels
)

plt.scatter(
    centroids[:,0],
    centroids[:,1],
    marker='X',
    s=200
)

plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")

plt.title("K-Means Clustering on Iris Dataset")

plt.show()

wcss = []

for i in range(1,11):

    kmeans = KMeans(
        n_clusters=i,
        random_state=42
    )

    kmeans.fit(X)

    wcss.append(kmeans.inertia_)

plt.figure(figsize=(8,6))

plt.plot(range(1,11), wcss)

plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")

plt.title("Elbow Method")

plt.show()

