# -*- coding: utf-8 -*-
"""hierarchical_clustering_customers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YBJ7FDvPle3EZQdT6ePNWEKMx61-oGMF
"""

import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt

from sklearn.cluster import AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram, linkage

import kagglehub

path = kagglehub.dataset_download(
    "shwetabh123/mall-customers"
)

print(path)

csv_path = os.path.join(path, "Mall_Customers.csv")

df = pd.read_csv(csv_path)

print(df.head())

X = df[['Annual Income (k$)', 'Spending Score (1-100)']]

print(X.head())

plt.figure(figsize=(8,6))

plt.scatter(
    X['Annual Income (k$)'],
    X['Spending Score (1-100)']
)

plt.xlabel("Annual Income")

plt.ylabel("Spending Score")

plt.title("Customers Dataset")

plt.show()

plt.figure(figsize=(10,6))

dendrogram(
    linkage(X, method='ward')
)

plt.title("Dendrogram")

plt.xlabel("Customers")

plt.ylabel("Euclidean Distance")

plt.show()

hc = AgglomerativeClustering(
    n_clusters=5,
    metric='euclidean',
    linkage='ward'
)

labels = hc.fit_predict(X)

print(labels)

plt.figure(figsize=(8,6))

plt.scatter(
    X.iloc[:,0],
    X.iloc[:,1],
    c=labels
)

plt.xlabel("Annual Income")

plt.ylabel("Spending Score")

plt.title("Hierarchical Clustering on Customers Dataset")

plt.show()

