# -*- coding: utf-8 -*-
"""dbscan_on_iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_gYJi0nH2CWM3maLny3jv9FeysfDplPp
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN

iris = load_iris()

X = iris.data

print("Shape of Dataset:", X.shape)

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

dbscan = DBSCAN(eps=0.8, min_samples=5)

clusters = dbscan.fit_predict(X_scaled)

print(clusters)

plt.figure(figsize=(8,6))

scatter = plt.scatter(
    X_scaled[:, 0],
    X_scaled[:, 1],
    c=clusters
)

plt.xlabel("Feature 1")
plt.ylabel("Feature 2")

plt.title("DBSCAN Clustering on Iris Dataset")

plt.show()

unique_clusters = np.unique(clusters)

print("Clusters Found:", unique_clusters)

