# -*- coding: utf-8 -*-
"""LDA_on_cats_dogs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18qMkh8yjttpjW0j3ZiIOamJPiZolMLjc
"""

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

import kagglehub

# Download latest version
path = kagglehub.dataset_download("bhavikjikadara/dog-and-cat-classification-dataset")

print("Path to dataset files:", path)

pet_path = os.path.join(path, 'PetImages')

cats_path = os.path.join(pet_path, 'Cat')
dogs_path = os.path.join(pet_path, 'Dog')

data = []
labels = []

IMG_SIZE = 64

for img_name in os.listdir(cats_path)[:500]:

    try:
        img_path = os.path.join(cats_path, img_name)

        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

        data.append(img.flatten())

        labels.append(0)

    except:
        pass

for img_name in os.listdir(dogs_path)[:500]:

    try:
        img_path = os.path.join(dogs_path, img_name)

        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

        data.append(img.flatten())

        labels.append(1)

    except:
        pass

X = np.array(data)
y = np.array(labels)

print("Original Shape:", X.shape)

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

lda = LinearDiscriminantAnalysis(n_components=1)

X_lda = lda.fit_transform(X_scaled, y)

print("Reduced Shape:", X_lda.shape)

plt.figure(figsize=(8,6))

plt.scatter(
    X_lda[y==0],
    np.zeros_like(X_lda[y==0]),
    label='Cats',
    alpha=0.6
)

plt.scatter(
    X_lda[y==1],
    np.zeros_like(X_lda[y==1]),
    label='Dogs',
    alpha=0.6
)

plt.xlabel("LDA Component")
plt.title("LDA on Cats and Dogs Dataset")

plt.legend()
plt.show()

