# -*- coding: utf-8 -*-
"""svd_on_mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAb1i2mXeixmPhgqLV-86HzJbYt325m3
"""

import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_digits
from sklearn.decomposition import TruncatedSVD

digits = load_digits()

X = digits.data
y = digits.target

print("Dataset Shape:", X.shape)

plt.figure(figsize=(10,4))

for i in range(5):

    plt.subplot(1,5,i+1)

    plt.imshow(digits.images[i], cmap='gray')

    plt.title(f"Label: {y[i]}")

    plt.axis('off')

plt.show()

svd = TruncatedSVD(n_components=2)

X_svd = svd.fit_transform(X)

print("Original Shape:", X.shape)
print("Reduced Shape:", X_svd.shape)

plt.figure(figsize=(8,6))

scatter = plt.scatter(
    X_svd[:,0],
    X_svd[:,1],
    c=y
)

plt.xlabel("SVD Component 1")
plt.ylabel("SVD Component 2")

plt.title("SVD on MNIST Digits Dataset")

plt.colorbar(scatter)

plt.show()

print("Explained Variance Ratio:")

print(svd.explained_variance_ratio_)

