# -*- coding: utf-8 -*-
"""forward-selection_backward-elimination.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ViQugZiupwcYMevfDlZWwbem1RuYvvRd

Theory

Feature selection is the process of selecting the most important features from a dataset.

It helps:

improve model performance
reduce overfitting
reduce computation time

Two common techniques are:

Forward Selection
Backward Elimination
1. Forward Selection
Theory

Forward Selection starts with no features and adds features one by one based on model performance.
2. Backward Elimination

Backward Elimination starts with all features and removes the least important features one by one.
"""

import pandas as pd

from sklearn.datasets import load_iris
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import SequentialFeatureSelector

iris = load_iris()

X = pd.DataFrame(iris.data, columns=iris.feature_names)

y = iris.target

print(X.head())

model = LinearRegression()

forward_selector = SequentialFeatureSelector(
    model,
    n_features_to_select=2,
    direction='forward'
)

forward_selector.fit(X, y)

selected_features = X.columns[forward_selector.get_support()]

print("Selected Features:")

print(selected_features)

from sklearn.feature_selection import SequentialFeatureSelector

backward_selector = SequentialFeatureSelector(
    model,
    n_features_to_select=2,
    direction='backward'
)

backward_selector.fit(X, y)

selected_features_backward = X.columns[backward_selector.get_support()]

print("Selected Features:")

print(selected_features_backward)

